name: fastapi-app
services:
  - name: api
    build:
      # Point to your server directory
      context: ./server
    run:
      cmd: uvicorn main:app --host 0.0.0.0 --port 8080
    routes:
      - path: /
